senai_backend_cshtml/testes_de_consumo/att_2/Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace E_Players.Controllers {
        public class EquipeController : Controller

        {
            Equipe equipeModel = new Equipe ();
            public IActionResult Index () {
                ViewBag.Equipes = equipeModel.ReadAll ();
                return View ();
            }
            public IActionResult Cadastrar (IFormCollection form) {
                Equipe novaEquipe = new Equipe ();
                novaEquipe.IdEquipe = Int32.Parse (form["IdEquipe"]);
                novaEquipe.Nome = form["Nome"];

                // Upload Início
                var file = form.Files[0];
                var folder = Path.Combine (Directory.GetCurrentDirectory (), "wwwroot/img/Equipes");

                if (file != null) {
                    if (!Directory.Exists (folder)) {
                        Directory.CreateDirectory (folder);
                    }
                    //Copia a img para nosso sistema
                    var path = Path.Combine (Directory.GetCurrentDirectory (), "wwwroot/img/", folder, file.FileName);
                    using (var stream = new FileStream (path, FileMode.Create)) {
                        file.CopyTo (stream);
                    }
                    novaEquipe.Imagem = file.FileName;
                } else {
                    novaEquipe.Imagem = "padrao.png";
                }
                // Upload Final

                equipeModel.Create (novaEquipe);
                ViewBag.Equipes = equipeModel.ReadAll ();

                return LocalRedirect ("~/Equipe");
            }

            [Route ("[controller]/{id}")]
            public IActionResult Excluir (int id) {
                equipeModel.Delete (id);
                ViewBag.Equipes = equipeModel.ReadAll ();
                return LocalRedirect ("~/Equipe");
            }

        }
}

senai_backend_cshtml/testes_de_consumo/att_2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using att_2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;

namespace att_2.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController (ILogger<HomeController> logger) {
            _logger = logger;
        }

// mudei essa parte
        Noticias noticiasModel = new Noticias ();
        public IActionResult Index () {
            ViewBag.Noticias = noticiasModel.ReadAll ();
            return View ();
        }

        //funcionou mas nao está meio esticado
        //puxo os dados da model do noticias para a view da home

// tentei fazer com que os models venha para a view da home tbm
        public IActionResult Privacy () {
            return View ();
        }

        [ResponseCache (Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error () {
            return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

senai_backend_cshtml/testes_de_consumo/att_2/Views/Home/Index.cshtml
@Model
@{
    ViewData["Title"] = "Inicio";
}

    <main>
        <div class="banner">
            <a asp-controller="Equipe" asp-action="Index" class="btn gradient">INSCREVA-SE</a>
        </div>

        <div class="sobre">
            <div class="container">
                <div>
                    <h1>O QUE É MUNDO EM COMUM ?</h1>
                    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis corporis voluptas odio
                        asperiores officia, quisquam eius optio itaque nobis vel. Amet placeat veniam architecto magni
                        at facere eaque adipisci laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. At
                        ipsum, veniam ad, illum corrupti nisi fugiat repellat harum aspernatur cupiditate aperiam
                        voluptatibus nulla a excepturi facere id non nemo totam! Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Cum numquam expedita architecto quia debitis sint consequatur! Deleniti sed
                        itaque illum aut officiis, quasi tempora esse id incidunt consequatur, magni ipsa? Lorem ipsum
                        dolor, sit amet consectetur adipisicing elit. Natus, beatae ullam iure blanditiis dolorum illum
                        excepturi tempore a unde, ipsa facilis aut et tempora nam quaerat nemo saepe, minus eaque. Lorem
                        ipsum dolor sit amet consectetur adipisicing elit. Tempore ab recusandae, consectetur dicta
                        molestias aliquid eligendi laboriosam sint optio dolor, accusantium quasi eius ad, placeat atque
                        harum veniam fuga sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet </p>
                </div>
            </div>
        </div>
        <img src="Images/9a6e4f50b0d94f75ce274348f06a6d56.png" alt="Imagem de um 
    campeão do lol" class="champion">

        <section id="horarios">

            <div class="container">
                <div class="ao_vivo">
                    <h2>AO VIVO</h2>
                    <div class="partida">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                </div>

                <div class="em_breve">
                    <h2>EM BREVE</h2>
                    <div class="partida">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="partida">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="partida">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                </div>
            </div>
        </section>

        <div class="container content">


            <section class="noticias">

            @foreach(var data in ViewBag.Noticias){
        
            <div class="card">
                    <img src="img/Noticias/@data.Imagem" alt="Notícia sobre @data.Titulo">
                    <div>
                        <h4>@data.Titulo</h4>
                        <p> @data.Texto</p>
                    </div>
            </div>
}
</section>

            <section class="recentes" id="resultados">
                <h3>PARTIDAS RECENTES</h3>

                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <div class="resultado">
                    <div class="team">
                        <strong>SK</strong>
                        <img src="Images/SK.png" alt="Logo da equipe SK">
                        <I>VS</I>
                        <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                        <strong>FLA</strong>
                    </div>
                    <div class="placar">
                        <P>3 x 2</p>
                    </div>
                </div>
                <a href="todos_os_resultados.html" class="btn gradient">mais resultados</a>
            </section>
        </div>

    </main>